# Multiple Linear Regression

## Import the libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime
from sklearn.metrics import r2_score

In [2]:
print(sys.path)

['/Users/ballakeerthi/dev/Airflow/ML background work', '/Users/ballakeerthi/opt/anaconda3/envs/airflow/lib/python39.zip', '/Users/ballakeerthi/opt/anaconda3/envs/airflow/lib/python3.9', '/Users/ballakeerthi/opt/anaconda3/envs/airflow/lib/python3.9/lib-dynload', '', '/Users/ballakeerthi/opt/anaconda3/envs/airflow/lib/python3.9/site-packages', '/Users/ballakeerthi/opt/anaconda3/envs/airflow/lib/python3.9/site-packages/IPython/extensions', '/Users/ballakeerthi/.ipython']


In [3]:
# url = "http://api.eia.gov/category/?api_key=97ceba422c30e187aa53b737datasetccab85&series_id=PET.RBRTE.D&category_id=241335"
# headers = {"name": "Europe Brent Spot Price FOB, Daily", "f": "D", "units": "Dollars per Barrel"}
# response = requests.get(url, headers)
# data = response.json()
# jsonFile = open("./brentcrude.json","w")
# json.dump(data, jsonFile)
# jsonFile.close()


## Import the dataset

In [4]:
dataset=pd.read_csv('Europe_Brent_Spot_Price_FOB.csv', sep='delimiter', header=None, parse_dates=True)
dataset[['Date','Price']]=dataset[0].str.split(',', expand=True)

/Users/ballakeerthi/opt/anaconda3/envs/airflow/lib/python3.9/site-packages/pandas/util/_decorators.py:311: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return func(*args, **kwargs)


In [5]:
type(dataset)

pandas.core.frame.DataFrame

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8772 entries, 0 to 8771
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       8772 non-null   object
 1   Date    8772 non-null   object
 2   Price   8768 non-null   object
dtypes: object(3)
memory usage: 205.7+ KB


In [7]:
list(dataset.columns.values)

[0, 'Date', 'Price']

In [8]:
dataset.dtypes

0        object
Date     object
Price    object
dtype: object

In [9]:
dataset=dataset.drop([0,1,2,3,4,5])
dataset=dataset.drop([0],axis=1)

In [10]:
dataset

Date  Price
6     11/26/2021  72.37
7     11/25/2021  82.05
8     11/24/2021  82.37
9     11/23/2021  83.43
10    11/22/2021  80.97
...          ...    ...
8767  05/26/1987  18.63
8768  05/25/1987   18.6
8769  05/22/1987  18.55
8770  05/21/1987  18.45
8771  05/20/1987  18.63

[8766 rows x 2 columns]

In [11]:
dataset['Date'] = pd.to_datetime(dataset['Date'])
dataset['Date'] = dataset['Date'].dt.strftime('%d.%m.%Y')
dataset['year'] = pd.DatetimeIndex(dataset['Date']).year
dataset['month'] = pd.DatetimeIndex(dataset['Date']).month
dataset['day'] = pd.DatetimeIndex(dataset['Date']).day
dataset['dayofyear'] = pd.DatetimeIndex(dataset['Date']).dayofyear
dataset['weekofyear'] = pd.DatetimeIndex(dataset['Date']).weekofyear
dataset['weekday'] = pd.DatetimeIndex(dataset['Date']).weekday
dataset['quarter'] = pd.DatetimeIndex(dataset['Date']).quarter
dataset['is_month_start'] = pd.DatetimeIndex(dataset['Date']).is_month_start
dataset['is_month_end'] = pd.DatetimeIndex(dataset['Date']).is_month_end
print(dataset.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8766 entries, 6 to 8771
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Date            8766 non-null   object
 1   Price           8766 non-null   object
 2   year            8766 non-null   int64 
 3   month           8766 non-null   int64 
 4   day             8766 non-null   int64 
 5   dayofyear       8766 non-null   int64 
 6   weekofyear      8766 non-null   int64 
 7   weekday         8766 non-null   int64 
 8   quarter         8766 non-null   int64 
 9   is_month_start  8766 non-null   bool  
 10  is_month_end    8766 non-null   bool  
dtypes: bool(2), int64(7), object(2)
memory usage: 702.0+ KB
None


/var/folders/b3/j_ybgjv53p33dy62wlktdr4m0000gp/T/ipykernel_33126/4141642202.py:7: FutureWarning: weekofyear and week have been deprecated, please use DatetimeIndex.isocalendar().week instead, which returns a Series.  To exactly reproduce the behavior of week and weekofyear and return an Index, you may call pd.Int64Index(idx.isocalendar().week)
  dataset['weekofyear'] = pd.DatetimeIndex(dataset['Date']).weekofyear


In [12]:
dataset=dataset.drop(['Date'],axis=1)

## Create Dummy Variables

In [13]:
dataset = pd.get_dummies(dataset, columns=['year'], drop_first=True, prefix='year')

dataset = pd.get_dummies(dataset, columns=['month'], drop_first=True, prefix='month')
dataset = pd.get_dummies(dataset, columns=['weekday'], drop_first=True, prefix='wday')
dataset = pd.get_dummies(dataset, columns=['quarter'], drop_first=True, prefix='qrtr')

dataset = pd.get_dummies(dataset, columns=['is_month_start'], drop_first=True, prefix='m_start')

dataset = pd.get_dummies(dataset, columns=['is_month_end'], drop_first=True, prefix='m_end')

dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8766 entries, 6 to 8771
Data columns (total 60 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Price         8766 non-null   object
 1   day           8766 non-null   int64 
 2   dayofyear     8766 non-null   int64 
 3   weekofyear    8766 non-null   int64 
 4   year_1988     8766 non-null   uint8 
 5   year_1989     8766 non-null   uint8 
 6   year_1990     8766 non-null   uint8 
 7   year_1991     8766 non-null   uint8 
 8   year_1992     8766 non-null   uint8 
 9   year_1993     8766 non-null   uint8 
 10  year_1994     8766 non-null   uint8 
 11  year_1995     8766 non-null   uint8 
 12  year_1996     8766 non-null   uint8 
 13  year_1997     8766 non-null   uint8 
 14  year_1998     8766 non-null   uint8 
 15  year_1999     8766 non-null   uint8 
 16  year_2000     8766 non-null   uint8 
 17  year_2001     8766 non-null   uint8 
 18  year_2002     8766 non-null   uint8 
 19  year_2

In [14]:
dataset['Price'] = dataset['Price'].astype('float')

In [15]:
dataset.dtypes

Price           float64
day               int64
dayofyear         int64
weekofyear        int64
year_1988         uint8
year_1989         uint8
year_1990         uint8
year_1991         uint8
year_1992         uint8
year_1993         uint8
year_1994         uint8
year_1995         uint8
year_1996         uint8
year_1997         uint8
year_1998         uint8
year_1999         uint8
year_2000         uint8
year_2001         uint8
year_2002         uint8
year_2003         uint8
year_2004         uint8
year_2005         uint8
year_2006         uint8
year_2007         uint8
year_2008         uint8
year_2009         uint8
year_2010         uint8
year_2011         uint8
year_2012         uint8
year_2013         uint8
year_2014         uint8
year_2015         uint8
year_2016         uint8
year_2017         uint8
year_2018         uint8
year_2019         uint8
year_2020         uint8
year_2021         uint8
month_2           uint8
month_3           uint8
month_4           uint8
month_5         

In [16]:
print(dataset)

      Price  day  dayofyear  weekofyear  year_1988  year_1989  year_1990  \
6     72.37   26        330          47          0          0          0   
7     82.05   25        329          47          0          0          0   
8     82.37   24        328          47          0          0          0   
9     83.43   23        327          47          0          0          0   
10    80.97   22        326          47          0          0          0   
...     ...  ...        ...         ...        ...        ...        ...   
8767  18.63   26        146          22          0          0          0   
8768  18.60   25        145          22          0          0          0   
8769  18.55   22        142          21          0          0          0   
8770  18.45   21        141          21          0          0          0   
8771  18.63   20        140          21          0          0          0   

      year_1991  year_1992  year_1993  ...  wday_2  wday_3  wday_4  wday_5  \
6        

In [17]:
x=dataset.iloc[:,1:].values

In [18]:
y=dataset.iloc[:,0].values

In [19]:
y=y.reshape(len(y),1)

In [20]:
x.shape

(8766, 59)

In [21]:
y.shape

(8766, 1)

In [22]:
print(x)

[[ 26 330  47 ...   1   0   0]
 [ 25 329  47 ...   1   0   0]
 [ 24 328  47 ...   1   0   0]
 ...
 [ 22 142  21 ...   0   0   0]
 [ 21 141  21 ...   0   0   0]
 [ 20 140  21 ...   0   0   0]]


In [23]:
print(y)

[[72.37]
 [82.05]
 [82.37]
 ...
 [18.55]
 [18.45]
 [18.63]]


## Split the dataset into training and test sets

In [24]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=1)

## Train the Multiple Linear Regression model on the Training Set

In [25]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [26]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(7012, 59)
(7012, 1)
(1754, 59)
(1754, 1)


## Predicting the Test Set results


In [27]:
y_pred = regressor.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[110.49 103.45]
 [ 66.31  67.57]
 [ 38.71  44.23]
 ...
 [ 18.    15.85]
 [ 66.4   67.01]
 [ 50.22  46.49]]


## Evaluating the Model Performance

In [28]:
r2_score(y_test,y_pred)

0.9365966016249414

In [51]:
from mysql.connector import connect,Error
from getpass import getpass
from sqlalchemy import create_engine
import pymysql
sqlEngine = create_engine('mysql+pymysql://airflowmysqluser:airflow@localhost/brent_pricing_db', pool_recycle=3600)
dbConnection = sqlEngine.connect()
tableName = "results_table"
try:
    results = pd.read_sql_table(tableName,dbConnection)
    # results = results.drop(['index'],axis=1)

except Error as e:
    print(e)

else:
    print("Dataset is created successfully")

# best_model=print(results[results['r_sq_score'] == results['r_sq_score'].max()])

index=results.r_sq_score.argmax()
best_model=results.iloc[results.r_sq_score.argmax(),0]
r_sq_score=results.iloc[results.r_sq_score.argmax(),1]
if best_model=='m_l_r':
    print("The best model is Multiple Linear Regression with R square score of ",r_sq_score)
elif best_model=='r_f_r':
    print("The best model is Random Forest Regression with R square score of ",r_sq_score)
else:
    print("The best model is Decision Tree Regression with R square score of ",r_sq_score)

Dataset is created successfully
The best model is Random Forest Regression with R square score of  0.993064
